### ISSUE TITLE
Commit https://github.com/Ylianst/ESP-IQ2020/commit/069a90cf201a7f8775e08d0242150acea616aa47 broke my configuration

### ISSUE THREAD

**Issue by richardpowellus** [Ylianst/ESP-IQ2020#49]
My configuration, which has been compiling perfectly up 'til now, suddenly stopped compiling and I believe it's due to this commit:
https://github.com/Ylianst/ESP-IQ2020/commit/069a90cf201a7f8775e08d0242150acea616aa47

The compile error I get is:

```
Compiling .pioenvs/hottub/src/esphome/components/iq2020/iq2020_text.cpp.o
In file included from src/esphome/components/iq2020/iq2020_text.cpp:2:
src/esphome/components/iq2020/iq2020_text.h:4:10: fatal error: esphome/components/text/text.h: No such file or directory
    4 | #include "esphome/components/text/text.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
*** [.pioenvs/hottub/src/esphome/components/iq2020/iq2020_text.cpp.o] Error 1
src/esphome/components/iq2020/iq2020.cpp: In member function 'void IQ2020Component::setTime(int, int, int, int, int, int)':
src/esphome/components/iq2020/iq2020.cpp:917:41: error: 'byte' was not declared in this scope; did you mean 'std::byte'?
  917 |         unsigned char setTimeCmd[] = { (byte)second, (byte)minute, (byte)hour, (byte)day, (byte)(month - 1), (byte)(year & 0xFF), (byte)(year >> 8) };
      |                                         ^~~~
      |                                         std::byte
In file included from /data/cache/platformio/packages/toolchain-xtensa-esp32/xtensa-esp32-elf/include/c++/12.2.0/cmath:42,
                 from src/esphome/core/component.h:3,
                 from src/esphome/components/iq2020/iq2020.h:2,
                 from src/esphome/components/iq2020/iq2020.cpp:1:
/data/cache/platformio/packages/toolchain-xtensa-esp32/xtensa-esp32-elf/include/c++/12.2.0/bits/cpp_type_traits.h:406:30: note: 'std::byte' declared here
  406 |   enum class byte : unsigned char;
      |                              ^~~~
src/esphome/components/iq2020/iq2020.cpp:917:46: error: expected '}' before 'second'
  917 |         unsigned char setTimeCmd[] = { (byte)second, (byte)minute, (byte)hour, (byte)day, (byte)(month - 1), (byte)(year & 0xFF), (byte)(year >> 8) };
      |                                      ~       ^~~~~~
src/esphome/components/iq2020/iq2020.cpp: At global scope:
src/esphome/components/iq2020/iq2020.cpp:918:26: error: expected constructor, destructor, or type conversion before '(' token
  918 |         sendIQ2020Command(0x01, 0x1F, 0x40, setTimeCmd, 7);
      |                          ^
src/esphome/components/iq2020/iq2020.cpp:919:1: error: expected declaration before '}' token
  919 | }
      | ^
*** [.pioenvs/hottub/src/esphome/components/iq2020/iq2020.cpp.o] Error 1
========================== [FAILED] Took 5.40 seconds ==========================
```

**Comment by Ylianst** [comment]
@richardpowellus - Ok, it should be fixed now. Let me know.

**Comment by Ylianst** [comment]
I will assume it's fixed. Please re-open if not.

**Comment by richardpowellus** [comment]
I seem to be getting a different proble now. And yes, I did "clean build files" in HomeAssistant and recompiled from scratch:

`Compiling .pioenvs/hottub/src/esphome/components/iq2020/iq2020_text.cpp.o
In file included from src/esphome/components/iq2020/iq2020_text.cpp:2:
src/esphome/components/iq2020/iq2020_text.h:4:10: fatal error: esphome/components/text/text.h: No such file or directory
    4 | #include "esphome/components/text/text.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
*** [.pioenvs/hottub/src/esphome/components/iq2020/iq2020_text.cpp.o] Error 1
========================= [FAILED] Took 36.16 seconds =========================`

**Comment by richardpowellus** [comment]
Yes, I did that. Unfortunately, the build is still failing with this error:

`Compiling .pioenvs/hottub/src/esphome/components/iq2020/iq2020_text.cpp.o
In file included from src/esphome/components/iq2020/iq2020_text.cpp:2:
src/esphome/components/iq2020/iq2020_text.h:4:10: fatal error: esphome/components/text/text.h: No such file or directory
    4 | #include "esphome/components/text/text.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
*** [.pioenvs/hottub/src/esphome/components/iq2020/iq2020_text.cpp.o] Error 1
========================= [FAILED] Took 39.24 seconds =========================`

Here's a video of the build process: https://1drv.ms/v/c/1c73de79c69c6c01/EYoYh6pu4bhNjA0QuK3ckcAB7wKo8nOyFQeOfvqZ8dL2wg?e=k8Woyu

**Comment by Ylianst** [comment]
oohhhh...ok. that is great info, i can fix that!!
